on: [push]
name: CI
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: ci/setup-docker-buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1          
      - name: ci/test-arm-build
        run: make docker-build

  lint:
    env:
      GOPATH: ${{ github.workspace }}

    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}/go.mod
        cache-dependency-path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}/go.sum
    - name: Lint code
      run: |
        make go-lint

  test:
    env:
      GOPATH: ${{ github.workspace }}

    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}/go.mod
        cache-dependency-path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}/go.sum
    - name: Execute Tests
      run: |
        go mod download
        go mod verify
        make test
